In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
data = pd.read_csv('CLEAR_DATASET.csv')
del data['Unnamed: 0']

In [3]:
data.head()

,rating,price,inbuilt memory,battery,display size,display hz,camera,smartphone
0,89.0,61048.89,256.0,5000.0,6.70,120.0,50.0,oneplus 11 5g
1,81.0,22187.79,128.0,5000.0,6.59,120.0,64.0,oneplus nord ce 2 lite 5g
2,75.0,18313.89,64.0,5000.0,6.60,90.0,50.0,samsung galaxy a14 5g
3,81.0,16648.89,128.0,5000.0,6.55,120.0,50.0,motorola moto g62 5g
4,82.0,27748.89,128.0,5000.0,6.70,120.0,108.0,realme 10 pro plus

In [4]:
input = ['40-50', 'Camera']

input = {'price': 45000.0, 'Camera':None, 'memory': None, 
         'battery':None, 'display':None, 'hz':None}

In [5]:
models = None

with open('models.pickle', 'rb') as file:
    models = pickle.load(file)

In [6]:
models

{'rating': KMeans(n_clusters=5, random_state=42),
 'price': KMeans(n_clusters=5, random_state=42),
 'inbuilt memory': KMeans(n_clusters=5, random_state=42),
 'battery': KMeans(n_clusters=5, random_state=42),
 'display size': KMeans(n_clusters=5, random_state=42),
 'display hz': KMeans(n_clusters=5, random_state=42),
 'camera': KMeans(n_clusters=5, random_state=42)}

In [7]:
X = np.array(data.price).reshape(-1, 1)
cluster_price = models['price'].predict(X)
to_send_data = data
for feature, cond in input.items():
    if cond is not None:
        predict = models[feature].predict([[cond]])
        print(predict)
to_send_data['price_pred'] = cluster_price
to_send_data = to_send_data[to_send_data['price_pred'] == predict[0]]
to_send_data

[0]

,rating,price,inbuilt memory,battery,display size,display hz,camera,smartphone,price_pred
4,82.0,27748.89,128.0,5000.0,6.70,120.0,108.0,realme 10 pro plus,0
7,86.0,33298.89,256.0,4980.0,6.67,120.0,200.0,xiaomi redmi note 12 pro plus,0
8,85.0,29691.39,128.0,4500.0,6.55,120.0,50.0,nothing phone 1,0
9,84.0,32188.89,128.0,4500.0,6.43,90.0,50.0,oneplus nord 2t 5g,0
12,79.0,27485.82,128.0,5000.0,6.67,120.0,50.0,xiaomi redmi note 12 pro 5g,0
...,...,...,...,...,...,...,...,...,...
938,87.0,47718.90,128.0,4500.0,6.67,144.0,50.0,motorola edge 40 fusion,0
942,86.0,36618.90,256.0,5000.0,6.70,120.0,64.0,xiaomi civi 3,0
948,83.0,38838.90,128.0,5000.0,6.67,120.0,64.0,motorola moto edge s30 pro,0
950,85.0,32178.90,256.0,5080.0,6.60,144.0,64.0,poco x4 gt 5g (8gb ram + 256gb),0
952,74.0,27738.90,128.0,5000.0,6.50,60.0,64.0,samsung galaxy m52s 5g,0

In [8]:
to_send_data = to_send_data.sort_values(by=['price', 'camera'], ascending=False).head(3)
to_send_data = to_send_data[['price', 'smartphone']]

to_send_data

        price                                  smartphone
106  48838.89                                vivo v27 pro
361  48838.89  samsung galaxy s21 fe 5g (8gb ram + 256gb)
49   47728.89                       samsung galaxy a74 5g

Выборка была произведена по: 

Цене: 40000-50000

Камера

Часть была с помощью сортировки (камера) в pandas, **НО цену выбирала ML**